FROM python:3.11 AS builder

COPY ./configs/requirements-dev.txt /tmp/requirements-dev.txt
RUN pip install -r /tmp/requirements-dev.txt

RUN mkdir /app
COPY ./src/ /app/backend/src/

WORKDIR /app/backend/src
CMD ["python3","-m","main"]
