name: 00 - Backend Test Workflow

on:
  push:
    branches-ignore:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2


      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Execute tests
        run: make test-local
